# Generated by Django 4.2.21 on 2025-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
