# Generated by Django 4.2.10 on 2025-05-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, verbose_name='Nome do Negócio')),
                ('business_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('business_address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('business_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('opening_time', models.TimeField(verbose_name='Horário de Abertura')),
                ('closing_time', models.TimeField(verbose_name='Horário de Fechamento')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberto')),
                ('delivery_available', models.BooleanField(default=True, verbose_name='Delivery Disponível')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pedido Mínimo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Imposto (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
