# Generated by Django 4.2.10 on 2025-05-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='business_photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_photos/', verbose_name='Foto do Restaurante'),
        ),
        migrations.AddField(
            model_name='settings',
            name='business_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Link Personalizado'),
        ),
    ]
