# Generated by Django 4.2.10 on 2025-05-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_openinghour'),
        ('settings', '0002_settings_business_photo_settings_business_slug'),
    ]

    operations = [
    ]
