# Generated by Django 4.2.10 on 2025-05-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_merge_20250520_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
