# Generated by Django 4.2.21 on 2025-05-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='payment_methods',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Formas de Pagamento'),
        ),
    ]
