# Generated by Django 4.2.21 on 2025-05-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settings_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
    ]
