# Generated by Django 4.2.10 on 2025-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_remove_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='next_day_closing',
            field=models.BooleanField(default=False, help_text='Indica se o fechamento é no dia seguinte'),
        ),
    ]
