# Generated by Django 4.2.21 on 2025-05-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_change_amount_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='change_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
