# Generated by Django 4.2.21 on 2025-05-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para'),
        ),
    ]
