# Generated by Django 4.2.21 on 2025-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_item_type_orderitem_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalhes de Personalização'),
        ),
    ]
