# Generated by Django 4.2.10 on 2025-05-24 23:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ingredientcategory_ingredient_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredient',
            name='is_addable',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='is_removable',
        ),
        migrations.AddField(
            model_name='productingredient',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='max_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product'),
        ),
    ]
