# Generated by Django 4.2.21 on 2025-05-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='Grupo do Produto'),
        ),
    ]
