# Generated by Django 4.2.10 on 2025-06-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productingredient_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('required_quantity', models.PositiveIntegerField(default=3, verbose_name='Quantidade Necessária')),
                ('reward_type', models.CharField(choices=[('SALADA', 'Salada'), ('SALPICAO', 'Salpicão')], max_length=20, verbose_name='Tipo de Brinde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone do Cliente')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual')),
                ('reward_claimed', models.BooleanField(default=False, verbose_name='Brinde Resgatado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='products.promotion')),
            ],
            options={
                'verbose_name': 'Progresso da Promoção',
                'verbose_name_plural': 'Progressos das Promoções',
                'unique_together': {('promotion', 'customer_phone')},
            },
        ),
    ]
