# Generated by Django 4.2.21 on 2025-06-02 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_promotion_promotionprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='reward_type',
            field=models.CharField(choices=[('salad', 'Salada'), ('salpicao', 'Salpicão')], default='salad', max_length=20, verbose_name='Tipo de Brinde'),
        ),
        migrations.AlterField(
            model_name='promotionprogress',
            name='reward_claimed',
            field=models.BooleanField(default=False, verbose_name='Brinde Reclamado'),
        ),
        migrations.CreateModel(
            name='PromotionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Grupo do Ingrediente')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('max_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade Máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.promotion')),
            ],
            options={
                'verbose_name': 'Ingrediente da Promoção',
                'verbose_name_plural': 'Ingredientes das Promoções',
                'unique_together': {('promotion', 'ingredient')},
            },
        ),
    ]
